# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"G\n\x11\x43reateTodoRequest\x12\x0e\n\x06userID\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"6\n\x12\x43reateTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0fGetTodosRequest\x12\x0e\n\x06userID\x18\x01 \x01(\x03\"B\n\x10GetTodosResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"C\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"6\n\x12UpdateTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"6\n\x12\x44\x65leteTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0eGetTodoRequest\x12\x0e\n\x06itemID\x18\x01 \x01(\x03\x12\x0e\n\x06userID\x18\x02 \x01(\x03\"A\n\x0fGetTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\xcd\x02\n\x0bTodoService\x12\x41\n\nCreateTodo\x12\x17.todo.CreateTodoRequest\x1a\x18.todo.CreateTodoResponse\"\x00\x12;\n\x08GetTodos\x12\x15.todo.GetTodosRequest\x1a\x16.todo.GetTodosResponse\"\x00\x12\x38\n\x07GetTodo\x12\x14.todo.GetTodoRequest\x1a\x15.todo.GetTodoResponse\"\x00\x12\x41\n\nUpdateTodo\x12\x17.todo.UpdateTodoRequest\x1a\x18.todo.UpdateTodoResponse\"\x00\x12\x41\n\nDeleteTodo\x12\x17.todo.DeleteTodoRequest\x1a\x18.todo.DeleteTodoResponse\"\x00\x42\x07Z\x05/todob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005/todo'
  _globals['_CREATETODOREQUEST']._serialized_start=20
  _globals['_CREATETODOREQUEST']._serialized_end=91
  _globals['_CREATETODORESPONSE']._serialized_start=93
  _globals['_CREATETODORESPONSE']._serialized_end=147
  _globals['_GETTODOSREQUEST']._serialized_start=149
  _globals['_GETTODOSREQUEST']._serialized_end=182
  _globals['_GETTODOSRESPONSE']._serialized_start=184
  _globals['_GETTODOSRESPONSE']._serialized_end=250
  _globals['_UPDATETODOREQUEST']._serialized_start=252
  _globals['_UPDATETODOREQUEST']._serialized_end=319
  _globals['_UPDATETODORESPONSE']._serialized_start=321
  _globals['_UPDATETODORESPONSE']._serialized_end=375
  _globals['_DELETETODOREQUEST']._serialized_start=377
  _globals['_DELETETODOREQUEST']._serialized_end=408
  _globals['_DELETETODORESPONSE']._serialized_start=410
  _globals['_DELETETODORESPONSE']._serialized_end=464
  _globals['_GETTODOREQUEST']._serialized_start=466
  _globals['_GETTODOREQUEST']._serialized_end=514
  _globals['_GETTODORESPONSE']._serialized_start=516
  _globals['_GETTODORESPONSE']._serialized_end=581
  _globals['_TODOSERVICE']._serialized_start=584
  _globals['_TODOSERVICE']._serialized_end=917
# @@protoc_insertion_point(module_scope)
